---
language: python
python: "2.7"
cache: pip

env:
  - JAVA_PRODUCT=jre JAVA_VERSION=7
  - JAVA_PRODUCT=jdk JAVA_VERSION=7
  - JAVA_PRODUCT=jre JAVA_VERSION=8
  - JAVA_PRODUCT=jdk JAVA_VERSION=8 
  - JAVA_PRODUCT=jre JAVA_VERSION=8 JAVA_DOWNLOAD_FOLDER_REMOTE=/tmp/ansible_download

addons:
  apt:
    packages:
    - python-pip

install:
  # Install Ansible.
  - pip install ansible==2.0.2.0

script:
  - "cd tests"
  - EXTRA_VARS="java_product=${JAVA_PRODUCT} java_version=${JAVA_VERSION}"
  - if [-z ${JAVA_DOWNLOAD_FOLDER_REMOTE}]; then EXTRA_VARS="${EXTRA_VARS} java_download_folder_remote=${JAVA_DOWNLOAD_FOLDER_REMOTE}"; fi

  # check syntax
  - ansible-playbook -i inventory test.yml --extra-vars="${EXTRA_VARS}" --syntax-check

  # run playbook
  - ansible-playbook -i inventory test.yml --extra-vars="${EXTRA_VARS}" --connection=local

  # run again to check if it is indempotent
  - >
    ansible-playbook -i inventory test.yml --extra-vars="${EXTRA_VARS}" --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # check that java is installed
  - >
    ${HOME}/sw/java/${JAVA_PRODUCT}1.${JAVA_VERSION}.0_*/bin/java -version
    && (echo 'Java is installed' && exit 0)
    || (echo 'Java is not installed' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
