---
language: python
python: "2.7"
cache: pip

env:
  - SITE=test.yml

addons:
  apt:
    packages:
    - python-pip

install:
  # Install Ansible.
  - pip install ansible==2.0.2.0

script:
  - "cd tests"

  # check syntax
  - "ansible-playbook -i inventory $SITE --syntax-check"

  # run playbook
  - "ansible-playbook -i inventory $SITE --connection=local --sudo"

  # run again to check if it is indempotent
  - >
    ansible-playbook -i inventory $SITE --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # check that java is installed
  - >
    which java
    && (echo 'Java is installed' && exit 0)
    || (echo 'Java is not installed' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
