---
- name: set download location on remote for java tar file
  set_fact:
    java_download_folder: "{{ java_download_folder_remote }}"

- name: get stat for download location
  stat:
    path: "{{ java_download_folder }}"
  register: java_download_folder_stat

- name: create download folder if it does not exist yet
  file:
    dest: "{{ java_download_folder }}"
    state: directory
  when: not ( java_download_folder_stat.isdir is defined and java_download_folder_stat.isdir ) and
        not ( java_download_folder_stat.islnk is defined and java_download_folder_stat.islnk )

- name: Download java to remote if we don't have it
  get_url:
    url:     "{{ java_download_url }}"
    dest:    "{{ java_download_folder ~ '/' ~ java_file_tar }}"
    headers: "Cookie:oraclelicense=accept-securebackup-cookie"
    force:   no
  tags: java_remote_download
