---
- name: unpack jce_policy
  unarchive:
    copy:    "{{ (java_download_folder_remote is defined) | ternary('no','yes') }}"
    src:     "{{ java_download_folder ~ '/' ~ java_oracle_jce_policy_file }}"
    dest:    "/tmp/"
    creates: "/tmp/UnlimitedJCEPolicyJDK8/local_policy.jar"

- name: create lib/security folder
  file:
    dest: "{{ java_unpack_dir ~ '/lib/security' }}"
    state: directory
  when: java_product == "jdk" 

- name: copy jce_policy
  copy:
    src: "/tmp/UnlimitedJCEPolicyJDK8/{{ item }}"
    dest: "{{ java_unpack_dir ~ '/lib/security/' ~ item }}"
  with_items:
    - local_policy.jar
    - README.txt
    - US_export_policy.jar
