---
- include: set_vars.yml

- include: download_to_master.yml
  when: java_download_folder_remote is undefined 

- include: download_to_remote.yml
  when: java_download_folder_remote is defined

- name: Create install directory
  file:
    dest: "{{ java_install_dir }}"
    state: directory
  tags: jdk_setup

- name: set directory where the archive will be extracted to
  set_fact:
    java_unpack_dir:   "{{ java_install_dir ~ '/' ~ java_product ~ '1.' ~ java_version ~ '.0_' ~ java_update }}"
  when: not java_early_access

- name: set directory where the archive will be extracted to for early access
  set_fact:
    java_unpack_dir:   "{{ java_install_dir ~ '/' ~ java_product ~ '-' ~ java_version }}"
  when: java_early_access

- name: unpack archive from master
  unarchive:
    copy:    "{{ (java_download_folder_remote is defined) | ternary('no','yes') }}"
    src:     "{{ java_download_folder ~ '/' ~ java_file_tar }}"
    dest:    "{{ java_install_dir }}"
    creates: "{{ java_unpack_dir }}"
#    extra_opts: ["--strip-components=1"]
  tags: jdk_setup

- name: install jce_policy
  include: jce_policy.yml
  when: (java_version|int == 8) and (java_oracle_jce_policy)

- name: setup shell
  include: shell_config.yml
  when: java_shell_profile
  tags: jdk_setup
