---
- include: set_vars.yml

- include: download_to_master.yml

- name: Create install directory
  file:
    dest: "{{ java_install_dir }}"
    state: directory
  tags: jdk_setup

- name: set directory where the archive will be extracted to
  set_fact:
    java_unpack_dir:   "{{ java_install_dir ~ '/jdk1.' ~ java_version ~ '.0_' ~ java_update }}"

- debug:
    var: java_unpack_dir

- name: unpack archive from master
  unarchive:
    src:     "{{ java_master_download_folder ~ '/' ~ java_file_tar }}"
    dest:    "{{ java_install_dir }}"
    creates: "{{ java_unpack_dir }}"
#    extra_opts: ["--strip-components=1"]
  tags: jdk_setup

- name: setup shell
  include: shell_config.yml
  when: java_shell_profile
  tags: jdk_setup
