---
- include: set_vars.yml

- include: download_to_master.yml

- name: Create install directory
  file:
    dest: "{{ java_install_dir }}"
    state: directory
  when: jdk_download.changed
  tags: jdk_setup

- name: unpack archive from master
  unarchive:
    src:  "{{ java_master_src }}"
    dest: "{{ java_install_dir }}"
    extra_opts: ["--strip-components=1"]
    mode: "0644"

- name: setup shell
  include: shell_config.yml
  when: java_shell_profile
  tags: jdk_setup
