---
- name: set java vars from defaults or settings
  set_fact:
    java_arch:        "{{ java_arch   | default( java_oracle_defaults.archmap[ansible_architecture] ) }}"
    java_os:          "{{ java_os     | default( java_oracle_defaults.osmap[ansible_system] ) }}"

- include: "set_vars_{{ java_version }}.yml"

- name: set java install dir
  set_fact:
    java_install_dir:  "{{ java_install_dir | default( ansible_env.HOME ~ '/sw/java' ) }}"

- name: set .profile path
  set_fact:
    java_oracle_profile_path: "{{ ansible_env.HOME ~ '/' ~ java_oracle_profile_file }}"
